server:
  port: 13377

spring:
  application:
      name: notification-service
  # Database Credentials
  datasource:
    username: ${ADMIN_ROLE}
    password: ${ADMIN_PASS}
    url: jdbc:postgresql://rev-project3.chvwilb5xwei.us-east-1.rds.amazonaws.com:5432/postgres
  # hbm2ddl 
  jpa:
    hibernate:
      ddl-auto: update
security:
  zsign:
    secret: ${RPM_ZUUL_ACCESS_HEADER}
    salt: ${RPM_ZUUL_ACCESS_SALT}