server:
  port: 8080

spring:
  application:
      name: spring-orm-demo
  # Database Credentials
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://rev-project3.chvwilb5xwei.us-east-1.rds.amazonaws.com:5432/postgres
    username: ${ADMIN_ROLE}
    password: ${ADMIN_PASS}
  # hbm2ddl 
  jpa:
    hibernate:
      ddl-auto: update